# Generated by Django 4.1.2 on 2022-10-15 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Persona", new_name="Familiar",),
    ]
