# Generated by Django 4.1.2 on 2022-10-31 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0004_mascota_delete_persona"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mascota",
            name="fecha_publicacion",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 31, 20, 43, 5, 886320)
            ),
        ),
    ]
