# Generated by Django 4.1.2 on 2022-10-31 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0005_alter_mascota_fecha_publicacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mascota",
            name="fecha_publicacion",
            field=models.DateTimeField(),
        ),
    ]
