# Generated by Django 4.1.2 on 2022-11-01 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0006_alter_mascota_fecha_publicacion"),
    ]

    operations = [
        migrations.RemoveField(model_name="mascota", name="fecha_publicacion",),
    ]
