# Generated by Django 4.1.2 on 2022-11-08 02:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0007_remove_mascota_fecha_publicacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="mascota",
            name="descripcion",
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
