# Generated by Django 4.1.2 on 2022-11-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0008_mascota_descripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="mascota",
            name="fecha_publicacion",
            field=models.DateTimeField(null=True),
        ),
    ]
